=== benceurikovacs/O3AE4K_XMLgyak/XMLTaskO3AE4K/DOMParseO3AE4K/XMLSchemaO3AE4K.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="model">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Futarok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Futar" type="Futar_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Italkereskedesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Italkereskedes" type="Italkereskedes_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Rendelesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rendeles" type="Rendeles_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Vevok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Vevo" type="Vevo_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Futar_Italkereskedes_kapcsolok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Futar_Italkereskedes" type="Futar_Italkereskedes_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Italkereskedes_Rendeles_kapcsolok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Italkereskedes_Rendeles" type="Italkereskedes_Rendeles_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Rendeles_Vevo_kapcsolok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rendeles_Vevo" type="Rendeles_Vevo_kapcsolo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:complexType name="Futar_type">
        <xs:sequence>
            <xs:element name="futarnev"></xs:element>
            <xs:element name="telefonszam"></xs:element>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Italkereskedes_type">
        <xs:sequence>
            <xs:element name="nyitvatartas"></xs:element>
            <xs:element name="elerhetoseg" type="elerhetoseg_type"></xs:element>
            <xs:element name="italkernev"></xs:element>
        </xs:sequence>
        <xs:attribute name="ikod" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Rendeles_type">
        <xs:sequence>
            <xs:element name="tetelek"></xs:element>
            <xs:element name="teljesar"></xs:element>
            <xs:element name="datum"></xs:element>
        </xs:sequence>
        <xs:attribute name="rkod" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Vevo_type">
        <xs:sequence>
            <xs:element name="telefonszam"></xs:element>
            <xs:element name="cim" type="cim_type"></xs:element>
            <xs:element name="nev"></xs:element>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Futar_Italkereskedes_kapcsolo">
        <xs:attribute name="Futarref" type="xs:integer" use="required"></xs:attribute>
        <xs:attribute name="Italkereskedesref" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Italkereskedes_Rendeles_kapcsolo">
        <xs:attribute name="Italkereskedesref" type="xs:integer" use="required"></xs:attribute>
        <xs:attribute name="Rendelesref" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="Rendeles_Vevo_kapcsolo">
        <xs:attribute name="Rendelesref" type="xs:integer" use="required"></xs:attribute>
        <xs:attribute name="Vevoref" type="xs:integer" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="elerhetoseg_type">
        <xs:sequence>
            <xs:element name="telefonszam"></xs:element>
            <xs:element name="webshopcime"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cim_type">
        <xs:sequence>
            <xs:element name="varos"></xs:element>
            <xs:element name="uhszam"></xs:element>
            <xs:element name="iranyitoszam"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="ItalkereskedÃ©srendszer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Futarok" type="Futar_type"/>
                <xs:element name="Italkereskedesek" type="Italkereskedes_type"/>
                <xs:element name="Rendelesek" type="Rendeles_type"/>
                <xs:element name="Vevok" type="Vevo_type"/>
                <xs:element name="Munka" type="Futar_Italkereskedes_kapcsolo"/>
            </xs:sequence>
        </xs:complexType>

		<xs:key name="Futar_EKulcs">
            <xs:selector xpath="Futarok/Futar"/>
            <xs:field xpath="@FID"/>
        </xs:key>

		<xs:key name="Italkereskedes_EKulcs">
            <xs:selector xpath="Italkereskedesek/Italkereskedes"/>
            <xs:field xpath="@IID"/>
        </xs:key>

		<xs:key name="Rendeles_EKulcs">
            <xs:selector xpath="Rendelesek/Rendeles"/>
            <xs:field xpath="@RID"/>
        </xs:key>

		<xs:key name="Vevo_EKulcs">
            <xs:selector xpath="Vevok/Vevo"/>
            <xs:field xpath="@VID"/>
        </xs:key>

		<xs:keyref name="Futar_IKulcs" refer="Futar_EKulcs">
            <xs:selector xpath="PFutarok/Futar"/>
            <xs:field xpath="@FIDRef"/>
        </xs:keyref>

		<xs:keyref name="Italkereskedes_IKulcs" refer="Italkereskedes_EKulcs">
            <xs:selector xpath="Munkak/Munka"/>
            <xs:field xpath="@IIDRef"/>
        </xs:keyref>

		<xs:keyref name="Rendeles_IKulcs" refer="Rendeles_EKulcs">
            <xs:selector xpath="Vasarlasok/Megveszi"/>
            <xs:field xpath="@RIDRef"/>
        </xs:keyref>

		<xs:keyref name="Vevo_IKulcs" refer="Vevo_EKulcs">
            <xs:selector xpath="Vasarlasok/Megveszi"/>
            <xs:field xpath="@VIDRef"/>
        </xs:keyref>
	</xs:element>

</xs:schema>

=== benceurikovacs/O3AE4K_XMLgyak/XMLTaskO3AE4K/DOMParseO3AE4K/XMLO3AE4K.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaO3AE4K.xsd">
<Futarok>
    <Futar fkod="1">
        <futarnev>Kiss Tamás</futarnev>
        <telefonszam>06307842588</telefonszam>
    </Futar>
    <Futar fkod="2">
        <futarnev>Nagy Gábor</futarnev>
        <telefonszam>06309761433</telefonszam>
    </Futar>
    <Futar fkod="3">
        <futarnev>Szabó Attila</futarnev>
        <telefonszam>06309752464</telefonszam>
    </Futar>
</Futarok>
<Italkereskedesek>
    <Italkereskedes ikod="1">
        <nyitvatartas>08:00-16:00</nyitvatartas>
        <elerhetoseg>
            <telefonszam>06303654891</telefonszam>
            <webshopcime>www.fovarosiitalkereskedes.hu</webshopcime>
        </elerhetoseg>
        <italkernev>Fővárosi Italkereskedés</italkernev>
    </Italkereskedes>
    <Italkereskedes ikod="2">
        <nyitvatartas>08:00-16:00</nyitvatartas>
        <elerhetoseg>
            <telefonszam>06307412588</telefonszam>
            <webshopcime>www.kecskemetinagyker.hu</webshopcime>
        </elerhetoseg>
        <italkernev>Kecskeméti Nagyker</italkernev>
    </Italkereskedes>
    <Italkereskedes ikod="3">
        <nyitvatartas>08:00-16:00</nyitvatartas>
        <elerhetoseg>
            <telefonszam>06308842671</telefonszam>
            <webshopcime>www.miskolcitaldiszkont.hu</webshopcime>
        </elerhetoseg>
        <italkernev>Miskolc Italdiszkont</italkernev>
    </Italkereskedes>
</Italkereskedesek>
<Rendelesek>
    <Rendeles rkod="1">
        <tetelek>1 rekesz sör</tetelek>
        <teljesar>4300</teljesar>
        <datum>2021.11.12.</datum>
    </Rendeles>
    <Rendeles rkod="2">
        <tetelek>5 rekesz sör</tetelek>
        <teljesar>21600</teljesar>
        <datum>2021.11.02.</datum>
    </Rendeles>
    <Rendeles rkod="3">
        <tetelek>15 rekesz sör</tetelek>
        <teljesar>64800</teljesar>
        <datum>2021.11.07</datum>
    </Rendeles>
    <Rendeles rkod="4">
        <tetelek>2 rekesz sör</tetelek>
        <teljesar>8600</teljesar>
        <datum>2021.11.01.</datum>
    </Rendeles>
</Rendelesek>
<Vevok>
    <Vevo vkod="1">
        <telefonszam>06305741211</telefonszam>
        <cim>
            <varos>Csemő</varos>
            <uhszam>Ősz utca 4.</uhszam>
            <iranyitoszam>2713</iranyitoszam>
        </cim>
        <nev>Uri-Kovács Bence</nev>
    </Vevo>
    <Vevo vkod="2">
        <telefonszam>03609874563</telefonszam>
        <cim>
            <varos>Miskolc</varos>
            <uhszam>Tél utca 18.</uhszam>
            <iranyitoszam>3515</iranyitoszam>
        </cim>
        <nev>Lakatos Brendon</nev>
    </Vevo>
    <Vevo vkod="3">
        <telefonszam>03601236544</telefonszam>
        <cim>
            <varos>Kecskemét</varos>
            <uhszam>Malom utca 1.</uhszam>
            <iranyitoszam>6000</iranyitoszam>
        </cim>
        <nev>Kovács László</nev>
    </Vevo>
</Vevok>

<Futar_Italkereskedes_kapcsolok>
    <Futar_Italkereskedes Futarref="1" Italkereskedesref="1"></Futar_Italkereskedes>
    <Futar_Italkereskedes Futarref="2" Italkereskedesref="2"></Futar_Italkereskedes>
    <Futar_Italkereskedes Futarref="2" Italkereskedesref="3"></Futar_Italkereskedes>
</Futar_Italkereskedes_kapcsolok>

<Italkereskedes_Rendeles_kapcsolok>
    <Italkereskedes_Rendeles Italkereskedesref="1" Rendelesref="1"></Italkereskedes_Rendeles>
    <Italkereskedes_Rendeles Italkereskedesref="1" Rendelesref="3"></Italkereskedes_Rendeles>
    <Italkereskedes_Rendeles Italkereskedesref="2" Rendelesref="2"></Italkereskedes_Rendeles>
    <Italkereskedes_Rendeles Italkereskedesref="2" Rendelesref="4"></Italkereskedes_Rendeles>
    <Italkereskedes_Rendeles Italkereskedesref="3" Rendelesref="5"></Italkereskedes_Rendeles>
</Italkereskedes_Rendeles_kapcsolok>

<Rendeles_Vevo_kapcsolok>
    <Rendeles_Vevo Rendelesref="1" Vevoref="2"></Rendeles_Vevo>
    <Rendeles_Vevo Rendelesref="2" Vevoref="4"></Rendeles_Vevo>
    <Rendeles_Vevo Rendelesref="3" Vevoref="5"></Rendeles_Vevo>
</Rendeles_Vevo_kapcsolok>
</model>
